# configs/obbpose11.yaml

experiment: "obbpose11"

data:
  root: "datasets"
  img_size: 768
  workers: 4
  pin_memory: true

model:
  num_classes: 1
  width: 0.5
  depth: 0.33
  strides: [4, 8, 16]

loss:
  lambda_box: 7.5
  lambda_obj: 3.0
  lambda_ang: 1.0
  lambda_kpt: 2.0
  lambda_cls: 1.0
  pos_obj_weight: 1.0
  soft_obj_warmup_epochs: 2
  kpt_freeze_epochs: 0
  kpt_warmup_epochs: 0
  assign_4_neighbors: true
  box_loss_type: "giou"   # "iou" or "giou"

decode:
  score_thresh: 0.25      # prefilter by score
  topk_per_level: 200     # keep per FPN level (P3,P4,P5)
  topk: 600               # global cap after concat
  apply_nms: true
  rotated_nms: false      # FAST mode (set true only if you have the kernels)
  nms_iou: 0.5
  max_det: 300            # final per-image cap after NMS


eval:
  interval: 1
  select: mAP50
  warmup_noeval_epochs: 0
  select_mode: max
  score_thresh: 0.3
  iou_thr: 0.2           # start loose; raise to 0.5 later
  pck_tau: 0.10          # start loose; tighten to 0.05 later
  max_det: 300
  topk: 100
  rank_by: "score"
  print_table: true
  iou_thrs: [0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95]

train:
  epochs: 10
  batch: 8
  lr: 0.001
  weight_decay: 0.0005
  amp: true
  seed: 42
  save_dir: "runs/exp"
  monitor: "map50"
  monitor_mode: "max"
  mosaic: true
  mosaic_prob: 0.5
  fliplr: 0.5
  flipud: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4

ddp:
  distributed: true
  backend: "nccl"
  find_unused_parameters: false
  broadcast_buffers: true

topdown:
  crop_size: 64          # crop side fed to kpt head
  expand: 1.25           # enlarge OBB before crop
  kpt_topk: 128          # cap ROIs per image (key!)
  score_thresh_kpt: 0.3 # drop very low-score boxes before cropping
  roi_chunk: 128         # process ROIs in chunks to bound memory

